[test]
preload = ["@testing-library/jest-dom", "./test-setup.ts"]
coverage = true
coverageDir = "coverage"
coverageReporter = ["text", "lcov"]
coverageSkipTestFiles = true
coveragePathIgnorePatterns = ["**/test-setup.ts", "**/__mocks__/**"]
coverageThreshold = { global = { branches = 100, functions = 100, lines = 100, statements = 100 } }